### ISSUE TITLE
Error while running node 

### ISSUE THREAD

**Issue by Viper-ui** [google-pay/pass-converter#10]
Getting the error below while running node app.js demo ....didn't do any changes in the code but still getting this error.
how to fix this?

D:\NodeJs\pass-converter-main\pass\index.js:208
      _strings.translatedValues ||= [];
                                ^^^

SyntaxError: Unexpected token '||='
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (D:\NodeJs\pass-converter-main\app.js:20:14)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)

**Comment by stephenmcd** [comment]
Which version of Node are you running? I believe at least version 15 is required, and earlier than that would cause the error you're seeing. If that's not the cause of the problem, please re-open the issue.
