### ISSUE TITLE
Getting DriverPackageNotInstalledError for SQLite

### ISSUE THREAD

**Issue by coderCK2** [google-pay/pass-converter#20]
I am attempting to run `node app.js` using my Bash shell on Windows, and I am encountering this error:
```
DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
    at SqliteDriver.loadDependencies (D:\OtherGithubProjects\pass-converter\node_modules\typeorm\driver\sqlite\SqliteDriver.js:143:19)
    at new SqliteDriver (D:\OtherGithubProjects\pass-converter\node_modules\typeorm\driver\sqlite\SqliteDriver.js:25:14)
    at DriverFactory.create (D:\OtherGithubProjects\pass-converter\node_modules\typeorm\driver\DriverFactory.js:44:24)
    at new DataSource (D:\OtherGithubProjects\pass-converter\node_modules\typeorm\data-source\DataSource.js:53:59)
    at Object.<anonymous> (D:\OtherGithubProjects\pass-converter\database.js:27:18)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
```

Running `npm install sqlite3 --save` is successful, though it did not solve the issue. I also have `sqlite3.exe` on my system path, which can be run successfully via the `sqlite3` command. However, I still encounter the above error. Any ideas about what is wrong with my config?

**Comment by coderCK2** [comment]
I decided to just completely remove the `pass-converter` directory and start from scratch with a new `git clone`. After doing this and the initial setup, there was no longer any error, and I successfully got the `Listening on http://127.0.0.1:3000` message. I don't know how the original error occurred, but it is fixed now. Closing this issue.

**Comment by stephenmcd** [comment]
Glad you resolved it, thanks for updating.
